### ISSUE TITLE
Transition to Azure AI Studio

### ISSUE THREAD

**Issue by mbilalamjad** [Azure-Samples/azure-openai-chat-baseline-landing-zone#6]
This issue is to track updates needed to be made to transition to AI Studio, a PR will be linked to this issue

Update
- Architecture Diagram
- Readme
- Updates to ACR, App Gateway, Jumpbox, keyvault, machinelearning, network, openai, storage, webapp

**Comment by mbilalamjad** [comment]
Reference https://github.com/Azure-Samples/openai-end-to-end-baseline/pull/25

**Comment by ckittel** [comment]
Addressed in #9
